# Generated by Django 5.0.4 on 2024-05-17 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
                ('profilepic', models.ImageField(upload_to='profilepics/')),
                ('dob', models.DateField()),
                ('paddress', models.TextField()),
                ('caddress', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('bcom', 'BCom'), ('bca', 'BCA'), ('mca', 'MCA')], max_length=10)),
                ('sem', models.CharField(blank=True, max_length=10, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('backlog', models.IntegerField(blank=True, null=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
