# Generated by Django 5.0.3 on 2024-11-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('svadmin', '0003_emailcontent_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_appeared', 'Not Appeared')], max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svadmin.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
