# Generated by Django 5.0.3 on 2024-12-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_aptitudetestresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AptitudeTestResult',
        ),
    ]
