# Generated by Django 5.0.3 on 2024-12-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_company'),
        ('svadmin', '0006_delete_eligiblestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligible_students', to='svadmin.company'),
        ),
    ]
