# Generated by Django 5.0.3 on 2024-12-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_company'),
        ('svadmin', '0006_delete_eligiblestudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligible_students', to='svadmin.company'),
        ),
        migrations.CreateModel(
            name='StudentCompanyAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_appeared', 'Not Appeared')], max_length=15)),
                ('test_date', models.DateField()),
                ('test_venue', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_associations', to='svadmin.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_associations', to='students.student')),
            ],
        ),
    ]
