# Generated by Django 5.0.3 on 2024-12-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_company_studentcompanyassociation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcompanyassociation',
            name='test_date',
        ),
        migrations.RemoveField(
            model_name='studentcompanyassociation',
            name='test_venue',
        ),
        migrations.AlterField(
            model_name='studentcompanyassociation',
            name='test_status',
            field=models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_appeared', 'Not Appeared')], default='not_appeared', max_length=15),
        ),
    ]
