# Generated by Django 5.0.3 on 2024-11-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_aptitudetestresult'),
        ('svadmin', '0003_emailcontent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='eligible_students',
            field=models.ManyToManyField(blank=True, related_name='email_contents', to='students.student'),
        ),
    ]
