# Generated by Django 5.0.3 on 2024-12-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_aptitudetestresult'),
        ('svadmin', '0004_emailcontent_eligible_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svadmin.company')),
                ('email_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svadmin.emailcontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
